version: '2'
services:
  blueprintdb:
    image: postgres:9.6
    container_name: blueprintdb
    environment:
      - POSTGRES_PASSWORD=aWJtX3VjZHAK
      - POSTGRES_USER=ibm_ucdp
      - POSTGRES_DATABASE=ibm_ucdp
    ports:
      - "5432:5432"
    restart: always
  ucddb:
    image: mysql:5.6
    container_name: ucddb
    environment:
      - MYSQL_ROOT_PASSWORD=aWJtX3VjZHAK
      - MYSQL_USER=ibm_ucd
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ibm_ucd
    ports:
      - "3306:3306"
    restart: always
  ucd:
    image: mkorejo/ucd-server:6.2.3
    container_name: ucd
    ports:
      - "7918:7918"
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - ucddb
    environment:
      - LICENSE=accept
      - DATABASE_USER=ibm_ucd
      - DATABASE_PASS=password
      - DATABASE_NAME=ibm_ucd
      - DATABASE_PORT=3306
      - DATABASE_HOST=ucddb
  agent:
    image: ibmcom/ucda:6.2.2.0
    container_name: agent
    hostname: "docker-ucda-$HOSTNAME"
    extra_hosts:
      - "ucd-server:ucd"
    links:
      - agent-relay
    restart: always
  agent-relay:
    image: ibmcom/ucdr:6.2.2.0
    container_name: agent-relay
    ports:
      - "20080:20080"
      - "20081:20081"
      - "7916:7916"
    environment:
      - PROXY_SERVERS=0.0.0.0:7918
      - SERVER_URL=https://ucd:8443
      - RELAY_HOST=0.0.0.0
      - AUTH_TOKEN=nopass
    links:
      - ucd
    restart: always
